[CmdletBinding()]
param([string]$RepositoryRoot)
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($RepositoryRoot)){$RepositoryRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path}
$ep=Join-Path $RepositoryRoot 'docs/bom/IPC100_RevA_EBOM.csv';$ap=Join-Path $RepositoryRoot 'docs/bom/Approved_Vendor_List.csv'
$ebom=@(Import-Csv $ep -Encoding UTF8);$avl=@(Import-Csv $ap -Encoding UTF8)
function E([string]$r){$x=$script:ebom|Where-Object Reference -eq $r|Select-Object -First 1;if($null-eq$x){throw "Missing EBOM $r"};$x}
function A([string]$i){$x=$script:avl|Where-Object Item -eq $i|Select-Object -First 1;if($null-eq$x){throw "Missing AVL $i"};$x}
function Block($x,[string]$risk){$x.'Freeze Status'='BLOCKED';$x.'Sourcing Risk'='BLOCKED - PACS-01R SYSTEM REVALIDATION';$x.'Requirement Trace Reference'='ECO-010; PACS-01R';$x.Risk=$risk;if($x.PSObject.Properties.Name-contains'Notes'){$x.Notes=$risk}}
function Active([string]$ref,[string]$value,[string]$role,[string]$mpn,[string]$package){$x=E $ref;$x.Value=$value;$x.Function=$value;$x.Description=$value;$x.'Electrical Role'=$role;$x.Manufacturer='Texas Instruments';$x.'Manufacturer Part Number'=$mpn;$x.Package=$package;$x.'Lifecycle Status'='ACTIVE - TI review 2026-07-31';$x.Availability='Orderable; stock requires PO revalidation';$x.'Preferred Vendor'='Texas Instruments';$x.'Preferred Vendor Ordering Code'=$mpn;Block $x "ECO-010 selectable implementation $mpn; BLOCKED - PACS-01R SYSTEM REVALIDATION; no footprint or procurement release.";$a=A $x.Item;$a.Manufacturer=$x.Manufacturer;$a.'Manufacturer Part Number'=$mpn;$a.Lifecycle=$x.'Lifecycle Status';$a.'Stock Status'=$x.Availability;$a.'Preferred Distributor'='Texas Instruments';$a.'Preferred Distributor Ordering Code'=$mpn;$a.'Review Date'='2026-07-31';Block $a $x.Risk}
Active 'U101' 'TPS26631PWPR 60 V eFuse; 20-pin PWP; adjustable OVP; 2x pulse support' 'IPC100:TPS26631_PWP' 'TPS26631PWPR' 'HTSSOP-20 PWP; footprint not assigned'
Active 'U801' 'TPS3899DL01 adjustable supervisor; OD active-low; external 2.9/2.7 V network; 6.2 ms' 'IPC100:TPS3899DL01' 'TPS3899DL01DSER' 'WSON-6 DSE; footprint not assigned'
foreach($r in @('U101','U801')){$x=E $r;$x.Risk='ANALYSIS INCOMPLETE - exact suffix/system revalidation remains required. '+$x.Risk;$x.Notes=$x.Risk;$a=A $x.Item;$a.Risk=$x.Risk}
foreach($pair in @(@('R806','150 kΩ ±0.1%, ≤25 ppm/°C - expansion-to-SENSE upper divider'),@('R808','1.30 MΩ ±0.1%, ≤25 ppm/°C - output-to-SENSE feedback'))){$x=E $pair[0];$x.Value=$pair[1];$x.Function=$pair[1];$x.Description=$pair[1];Block $x 'ECO-010 threshold dependency; BLOCKED - PACS-01R/PAS-01R.'}
function Clone([string]$template,[string]$ref,[string]$value,[string]$role){if($script:ebom|Where-Object Reference -eq $ref){return};$t=E $template;$n=$t.PSObject.Copy();$n.Item="08_Expansion/$ref";$n.Reference=$ref;$n.Value=$value;$n.Function=$value;$n.Description=$value;$n.'Electrical Role'=$role;$n.Manufacturer='UNRESOLVED - PACS-01R';$n.'Manufacturer Part Number'='UNRESOLVED - PACS-01R';$n.Package='UNRESOLVED - NO FOOTPRINT ASSIGNED';$n.'Lifecycle Status'='NOT REVIEWED - BLOCKED';$n.Availability='NOT REVIEWED - BLOCKED';$n.'Preferred Vendor'='UNRESOLVED';$n.'Preferred Vendor Ordering Code'='UNRESOLVED';Block $n 'New ECO-010 support element; exact passive MPN remains blocked; no footprint.';$script:ebom+=@($n);$ta=A $t.Item;$na=$ta.PSObject.Copy();$na.Item=$n.Item;$na.Manufacturer=$n.Manufacturer;$na.'Manufacturer Part Number'=$n.'Manufacturer Part Number';$na.Lifecycle=$n.'Lifecycle Status';$na.'Stock Status'=$n.Availability;$na.'Review Date'='2026-07-31';Block $na $n.Risk;$script:avl+=@($na)}
Clone 'R806' 'R807' '31.6 kΩ ±0.1%, ≤25 ppm/°C - TPS3899 SENSE lower divider' 'IPC100:R'
Clone 'R806' 'R809' '4.70 kΩ ±1% - TPS3899 output pull-up' 'IPC100:R'
Clone 'C804' 'C805' '10 nF ±10% X7R - TPS3899 CTR; 6.2 ms nominal' 'IPC100:C'
foreach($r in @('C805','R807','R808','R809')){$x=E $r;$x.Risk='PAS-01R: BLOCKED — ACTIVE DEVICE SELECTION REQUIRED. ECO-010 support element requires exact passive selection after PACS-01R.';$x.Notes=$x.Risk;$a=A $x.Item;$a.Risk=$x.Risk}
$x=E 'R806';$x.Risk='ANALYSIS INCOMPLETE - ECO-007 threshold-network evidence superseded by ECO-010; exact passive selection and PACS-01R system revalidation remain required.';$x.Notes=$x.Risk;$a=A $x.Item;$a.Risk=$x.Risk
foreach($x in $ebom|Where-Object{$_.Reference-in@('Q101','U102','U201','U202','U203','U204','U205','U206','U207','U208','U209','U210','U211','U212','U213','U302','U706','U707')}){$x.'Freeze Status'='BLOCKED';$x.'Sourcing Risk'='BLOCKED - PACS-01R SYSTEM REVALIDATION'}
$ebom=@($ebom|Sort-Object Sheet,Reference);$avl=@($avl|Sort-Object Item);$ebom|Export-Csv $ep -NoTypeInformation -Encoding UTF8;$avl|Export-Csv $ap -NoTypeInformation -Encoding UTF8
& python (Join-Path $RepositoryRoot 'scripts/csv_to_xlsx.py') $ep (Join-Path $RepositoryRoot 'docs/bom/IPC100_RevA_EBOM.xlsx');& python (Join-Path $RepositoryRoot 'scripts/csv_to_xlsx.py') $ap (Join-Path $RepositoryRoot 'docs/bom/Approved_Vendor_List.xlsx');if($LASTEXITCODE-ne 0){throw 'XLSX regeneration failed'}
Write-Host 'ECO-010 BOM/AVL overlay applied.'
