[CmdletBinding()]
param([string]$RepositoryRoot)
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) { $RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path }

$rows = @(Import-Csv (Join-Path $RepositoryRoot 'docs/bom/IPC100_RevA_EBOM.csv') -Encoding UTF8 | Where-Object { $_.'Selection Scope' -eq 'CSR-01A POWER' -and $_.'Freeze Status' -eq 'BLOCKED' } | Sort-Object Sheet,Reference)
function Clean([string]$Text) { return (($Text -replace '\|','/') -replace '[\r\n]+',' ') }
function EvidenceFor($row) {
  if ($row.Reference -eq 'J1') { return @('RC-D','Complete connector system requirements and order-code chain','QER/MIR electrical, thermal, environmental and harness envelope retained','JCS-01 exact housings, mate, contacts, seals, wire, tooling, lifecycle, sources and alternate','BLOCKED pending JCS-01') }
  if ($row.Risk -match '^TRANSIENT COORDINATION') { return @('RC-A','Stress/current/energy/leakage/fault coordination against a common source model','PEB-01 source cases, stress ladder, fuse/TVS/MOSF/current-limit equations and derating limits','Exact manufacturer curves/order code plus required surge, reverse, ESD, short and recovery tests','ELIGIBLE for exact freeze evaluation after PEB-01 selection evidence') }
  if ($row.Risk -match 'THERMAL/STABILITY|ECO-006|exact suffix|ECO-007|saturation|TCA9517A') { return @('RC-B','Operating-point, tolerance, stability, SOA and package-independent thermal envelope','PEB-01 load cases, loss/thermal limits, regulator/inductor/capacitor/MOSF equations and verification plan','Exact suffix/curves/vendor-tool results, commercial evidence and identified prototype correlation','ELIGIBLE for exact freeze evaluation after PEB-01 selection evidence') }
  if ($row.Risk -match 'exact dielectric') { return @('RC-C','Function-specific effective capacitance, bias, ripple, ESR, aging, voltage and lifetime evidence','PEB-01 rail stresses, ripple equations, derating rules and minimum effective-capacitance envelope','PPQ-01 exact manufacturer bias/ripple/aging curves, lifecycle, sources, alternate and cost','BLOCKED pending PPQ-01') }
  if ($row.Risk -match 'device equation') { return @('RC-C','Function-specific tolerance, tempco, voltage, power, pulse and failure-effect evidence','PEB-01 rail stresses, programming/threshold equations and derating rules','PPQ-01 exact resistor tolerance/voltage/pulse evidence, lifecycle, sources, alternate and cost','BLOCKED pending PPQ-01') }
  throw "Unclassified blocked row $($row.Item)"
}

$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine('# PEB-01 Appendix — Power Component Evidence Register')
[void]$builder.AppendLine()
[void]$builder.AppendLine('This register maps every post-DRA blocked power reference exactly once. PEB-01 generates package-independent analytical evidence; it does not select a component or alter the current EBOM disposition.')
[void]$builder.AppendLine()
[void]$builder.AppendLine('| Reference | Sheet | Root cause | Current blocker | Required evidence | Evidence generated by PEB-01 | Remaining evidence required | Expected disposition after CSR-01A-R4 |')
[void]$builder.AppendLine('|---|---|---|---|---|---|---|---|')
foreach ($row in $rows) {
  $e = EvidenceFor $row
  [void]$builder.AppendLine("| $($row.Reference) | $($row.Sheet) | $($e[0]) | $(Clean $row.Risk) | $($e[1]) | $($e[2]) | $($e[3]) | $($e[4]) |")
}
[void]$builder.AppendLine()
[void]$builder.AppendLine('## Coverage summary')
[void]$builder.AppendLine()
[void]$builder.AppendLine('- RC-A: 19 references; eligible for exact evaluation after PEB-01 plus manufacturer/prototype evidence.')
[void]$builder.AppendLine('- RC-B: 37 references; eligible for exact evaluation after PEB-01 plus manufacturer/prototype evidence.')
[void]$builder.AppendLine('- RC-C: 67 references; remains blocked pending PPQ-01 exact passive qualification.')
[void]$builder.AppendLine('- RC-D: 1 reference; remains blocked pending JCS-01.')
[void]$builder.AppendLine('- Total: 124 references, each represented once.')

$path = Join-Path $RepositoryRoot 'docs/analysis/Power_Component_Evidence_Register.md'
[IO.File]::WriteAllText($path, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "PEB-01 evidence register generated: $($rows.Count) blocked references."
